### ISSUE TITLE
error when i tried to extract a validation set

### ISSUE THREAD

**Issue by adelabdelli** [nagypeterjob/Sentiment-Analysis-NLTK-ML#1] opened 2018-03-11 23:45 UTC
Hello , i got this error when i tried to extract a validation set, and measuring score and accuracy :
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-23-580a17ec56d5> in <module>()
      5 X_test = X_test[:-validation_size]
      6 Y_test = Y_test[:-validation_size]
----> 7 score,acc = model.evaluate(X_test, Y_test, verbose = 0, batch_size = validation_size)
      8 print("score: %.2f" % (score))
      9 print("acc: %.2f" % (acc))

ValueError: not enough values to unpack (expected 2, got 0)
```

Why i got this error ?

**Comment by nagypeterjob** [comment] 2018-03-11 23:50
Please check what value unpacking means:
https://stackoverflow.com/questions/749070/partial-list-unpack-in-python

Are you running my original notebook? Or are you training with your own data?

**Comment by adelabdelli** [comment] 2018-03-11 23:54
i'm running my own data, what is the solution ?

**Comment by nagypeterjob** [comment] 2018-03-11 23:59
The solution is to check the dimensions of X_test, Y_test. And also check the documentation of  **model.evaluate**. 
https://keras.io/models/model/
The inputs cleary doesn't fit for **model.evaluate** so it produces no return value. I think the problem is the dimension of your data.

I can't provide you exact solution so I am closing this issue. Please don't open an issue when the problem is  with your own code.

**Closed as completed** 2018-03-11 23:59 UTC
